Fusion demande pour l'ajout d'une commande !bar
tofbot/tofbot pull request #27
Opened 2018-05-09 20:36 UTC by TaTaaaa

On aime aller au bar, mais tous les Michels ne sont pas sur IRC. Rameutons les grâce à notre esclave tofbot!

2018-05-10 11:03 UTC, p0nce commented
Ta fusio-demande contient des commits qui sont déjà mergés. 

C'est un cas où il peut être utile de rebaser sur le tofbot master, je conseille de suivre : https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository

En gros ca changera ton fork pour faire comme si il était master-de-tofbot + ton dernier commit alors que à l'heure actuelle il est master-de-tobbot-ancien + calculette de l'amour + ton dernier commit ce qui fait des noeuds dans l'historique.

2018-05-14 16:06 UTC, martinkirch requested changes
9/10 would review again

2018-05-14 16:06 UTC, martinkirch commented on bot.py
> +    nick = os.getenv("TOFBOT_NICK", "tofbot3")
laissons `tofbot` ! idem en-dessous

2018-05-14 16:06 UTC, martinkirch commented on plugins/amour.py
> +
toutes ces updates d'indentation auraient mérité leur propre fusiodemande MAIS OKER

2018-05-14 16:06 UTC, martinkirch commented on plugins/bar.py
> +        if sender_nick == "Pebz":
👍

2018-05-14 16:06 UTC, martinkirch commented on plugins/bar.py
> +        "envoie un email aux grelakins"
Va falloir anonymiser tout ça ! cette docstring, `from_address`, `recipient` 
Du coup pas de valeur par défaut pour les variables d'environnement, laissons planter si elles sont pas fournies.

2018-05-15 07:30 UTC, chmduquesne commented on plugins/bar.py
> +                    from_address = [u"Honorable tofbot",
ça serait bien de ne pas mettre l'adresse en dur, mais plutôt os.getenv("TOFBOT_EMAIL", "tofbot@ouahpiti.info")

2018-05-15 07:33 UTC, chmduquesne commented on plugins/bar.py
> +                    recipient = [u"Michels", os.getenv(
On risque de croire que TOFBOT_MAIL est l'email utilisé par tofbot. Je le renommerais TOFBOT_MAILING_LIST (et tant qu'à faire je mettrais l'option d'avoir plusieurs cibles, donc en faisant un split sur les virgules, comme pour la variable TOFBOT_CHAN)

2018-05-15 17:44 UTC, merged